alias l="ls"
alias gs="git status"
alias ga="git add ."
alias gc="git commit -am"
alias gl="git log --graph --oneline"
alias gd="git diff"
alias gps="git push"
alias gpl="git pull"

# below snippet generated by nvm installation script.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
